default:
  http_metas:
    content-type: text/html

  metas:
    title:        sup
    description:  sup: visual project board
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, screen.css]

  javascripts:    [jquery-1.3.2.js, sup.js]

  has_layout:     true
  layout:         layout
