default:
  http_metas:
    content-type: text/html

  metas:
    title:        sup
    description:  sup: visual project board
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, screen.css, jquery.ui/no-theme/jquery-ui-1.7.2.custom.css]

  javascripts:    [jquery-1.3.2.js, jquery.ui/ui.core.js, jquery.ui/ui.draggable.js, jquery.ui/ui.resizable.js, sup.js]

  has_layout:     true
  layout:         layout
