BlockData:
  actAs: [Timestampable]
  columns:
    title: string(255)
    description: text
    importance: integer

BlockPosition:
  actAs: [Timestampable]
  columns:
    width: float
    height: float
    position_x: float
    position_y: float

Block:
  columns:
    block_data_id: integer
    block_position_id: integer

  relations:
    BlockData:
      local: block_data_id
      foreign: id
      foreignType: one
    BlockPosition:
      local: block_position_id
      foreign: id
      foreignType: one